declare module "*.png";
declare module "*.jpg";
declare module "*.jpeg";
declare module "*.gif";
declare module "*.bmp";
declare module "*.tiff";
declare module "vue3-markdown-it";
declare module "*.geoJson";
declare module "TypeIt";
